# coding: utf-8

"""
    KCrud

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.contact_api import ContactApi


class TestContactApi(unittest.TestCase):
    """ContactApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ContactApi()

    def tearDown(self) -> None:
        pass

    def test_contact_get(self) -> None:
        """Test case for contact_get

        """
        pass

    def test_contact_id_delete(self) -> None:
        """Test case for contact_id_delete

        """
        pass

    def test_contact_id_get(self) -> None:
        """Test case for contact_id_get

        """
        pass

    def test_contact_id_put(self) -> None:
        """Test case for contact_id_put

        """
        pass

    def test_contact_post(self) -> None:
        """Test case for contact_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
